import fs from "node:fs";
import path from "node:path";

const repoRoot = process.cwd();
const vendorSrcRoot = path.join(repoRoot, "third_party", "ros_web_gui_app", "src");

const updates = [
  {
    file: "components/ConnectionPage.tsx",
    replacements: [
      ["请输入IP和端口", "Enter both host and port"],
      ["连接失败，请检查IP和端口是否正确", "Connection failed. Check the host and port."],
      ["连接失败", "Connection failed"],
      ["机器人连接", "Robot Connection"],
      ["IP地址:", "Host:"],
      ["端口:", "Port:"],
      ["连接中...", "Connecting..."],
      ["连接", "Connect"],
    ],
  },
  {
    file: "components/ManualControlPanel.tsx",
    replacements: [
      ["前进 (W / ↑)", "Forward (W / ↑)"],
      ["左转 (A / ←)", "Rotate Left (A / ←)"],
      ["后退 (S / ↓)", "Reverse (S / ↓)"],
      ["右转 (D / →)", "Rotate Right (D / →)"],
      ["左移 (Z)", "Strafe Left (Z)"],
      ["右移 (X)", "Strafe Right (X)"],
    ],
  },
  {
    file: "components/TopoPointInfoPanel.tsx",
    replacements: [
      ["已发布导航目标: ", "Navigation goal published: "],
      ["导航点信息", "Navigation Point"],
      ["名称:", "Name:"],
      ["单点导航", "Navigate Here"],
      ["路线信息", "Route Details"],
      ["起点:", "Start:"],
      ["终点:", "End:"],
      ["控制器:", "Controller:"],
      ["目标检查器:", "Goal Checker:"],
      ["速度限制:", "Speed Limit:"],
    ],
  },
  {
    file: "constants/layerConfigs.ts",
    replacements: [
      ["name: '网格'", "name: 'Grid'"],
      ["name: '栅格地图'", "name: 'Occupancy Grid'"],
      ["name: '局部代价地图'", "name: 'Local Costmap'"],
      ["name: '全局代价地图'", "name: 'Global Costmap'"],
      ["name: '激光雷达'", "name: 'Laser Scan'"],
      ["name: '机器人位置'", "name: 'Robot Pose'"],
      ["name: '局部路径'", "name: 'Local Plan'"],
      ["name: '全局路径'", "name: 'Global Plan'"],
      ["name: 'TF坐标系'", "name: 'TF Frames'"],
      ["name: 'Topology地图'", "name: 'Topology Map'"],
      ["name: '遥控'", "name: 'Manual Control'"],
      ["name: '重定位'", "name: 'Relocalize'"],
    ],
  },
  {
    file: "hooks/useConnectionInit.ts",
    replacements: [
      ["初始化失败，使用默认配置...", "Initialization failed. Falling back to default settings..."],
    ],
  },
  {
    file: "components/MapView.tsx",
    replacements: [
      ["切换视图模式", "Switching view mode"],
      ["全屏操作失败", "Fullscreen request failed"],
      ["无法发布初始化位姿", "Unable to publish initial pose"],
      ["初始化位姿已发布", "Initial pose published"],
      ["当前: ${viewMode === '2d' ? '2D' : '3D'}视图，点击切换到${viewMode === '2d' ? '3D' : '2D'}", "Current: ${viewMode === '2d' ? '2D' : '3D'} view. Click to switch to ${viewMode === '2d' ? '3D' : '2D'}"],
      ["图层配置", "Layer Settings"],
      ["地图编辑", "Map Editor"],
      ["退出全屏", "Exit fullscreen"],
      ["进入全屏", "Enter fullscreen"],
      ["退出手动控制", "Exit manual control"],
      ["手动控制", "Manual control"],
      ["退出重定位", "Exit relocalization"],
      ["重定位", "Relocalize"],
      ["确定", "Confirm"],
      ["取消", "Cancel"],
      ["取消跟随机器人", "Stop following robot"],
      ["CancelFollow robot", "Stop following robot"],
      ["跟随机器人", "Follow robot"],
      ["Follow robot", "Follow Robot"],
      ["📍 跟随中", "📍 Following"],
      ["📍 跟随机器人", "📍 Follow Robot"],
      ["📍 Follow robot", "📍 Follow Robot"],
      ["加载 URDF 模型失败: ", "Failed to load URDF model: "],
      ["未知错误", "Unknown error"],
      ["鼠标:", "Cursor:"],
      ["重定位位置:", "Relocalize Pose:"],
      ["Relocalize位置:", "Relocalize Pose:"],
      ["机器人:", "Robot:"],
    ],
  },
  {
    file: "components/LayerSettingsPanel.tsx",
    replacements: [
      ["正在解压 ZIP 文件...", "Extracting ZIP archive..."],
      ["ZIP 文件中未找到 URDF 文件", "No URDF file found in the ZIP archive"],
      ["已解压 ${filesToSave.size} 个文件", "Extracted ${filesToSave.size} files"],
      ["检测到 ${meshPaths.length} 个 mesh 文件引用。建议上传包含所有文件的 ZIP 压缩包。", "${meshPaths.length} mesh references detected. Uploading a ZIP archive with all assets is recommended."],
      ["请选择 URDF 文件或包含 URDF 的 ZIP 压缩包", "Choose a URDF file or a ZIP archive that contains one"],
      ["URDF 文件中未找到包引用，将使用相对路径加载 mesh 文件", "No package references found in the URDF. Relative mesh paths will be used."],
      ["URDF 文件已保存: ${urdfFileName}", "URDF saved: ${urdfFileName}"],
      ["上传 URDF 失败:", "URDF upload failed:"],
      ["上传 URDF 失败: ", "URDF upload failed: "],
      ["已切换 URDF 配置", "Switched active URDF configuration"],
      ["确定要删除 \"${config.fileName}\" 吗？", "Delete \"${config.fileName}\"?"],
      ["已删除 URDF 配置", "URDF configuration deleted"],
      ["删除失败: ", "Delete failed: "],
      ["URDF 文件已保存: ${selectedFileName}", "URDF saved: ${selectedFileName}"],
      ["处理 URDF 文件失败:", "Failed to process URDF file:"],
      ["处理 URDF 文件失败: ", "Failed to process URDF file: "],
      [") Manual Control ", ") ?? "],
      ["图层配置", "Layer Settings"],
      ["恢复默认设置", "Restore default settings"],
      ["恢复默认", "Reset"],
      ["遥控", "Manual Control"],
      ["重定位", "Relocalize"],
      ["话题:", "Topic:"],
      ["(无)", "(none)"],
      ["X轴速度 (前进/后退):", "X linear speed (forward/reverse):"],
      ["Y轴速度 (左右移动):", "Y linear speed (strafe):"],
      ["Z轴角速度 (旋转):", "Z angular speed (turn):"],
      ["暂无遥控配置", "No manual control configuration"],
      ["暂无Manual Control配置", "No manual control configuration"],
      ["暂无重定位配置", "No relocalization configuration"],
      ["图片", "Images"],
      ["添加", "Add"],
      ["名称:", "Name:"],
      ["类型:", "Type:"],
      ["确定要删除图层 \"${config.name}\" 吗？", "Delete layer \"${config.name}\"?"],
      ["删除", "Delete"],
      ["暂无图片图层", "No image layers"],
      ["暂无Images图层", "No image layers"],
      ["URDF 管理", "URDF Manager"],
      ["📤 上传 URDF 文件（ZIP 压缩包）", "📤 Upload URDF (ZIP archive)"],
      ["暂无已上传的 URDF 文件", "No uploaded URDF files"],
      ["当前使用", "Active"],
      ["个包", " packages"],
      ["使用", "Use"],
      ["颜色模式:", "Color Mode:"],
      ["透明度:", "Opacity:"],
      ["高度:", "Height:"],
      ["目标坐标系:", "Target Frame:"],
      ["基础坐标系:", "Base Frame:"],
      ["地图坐标系:", "Map Frame:"],
      ["跟随缩放倍数:", "Follow zoom factor:"],
      ["（越小越放大，范围：0.01-1）", "(Smaller values zoom in more. Range: 0.01-1)"],
      ["颜色:", "Color:"],
      ["线段宽度:", "Line Width:"],
      ["点大小:", "Point Size:"],
      ["显示frame名称:", "Show frame names:"],
      ["显示frameName:", "Show frame names:"],
      ["? '是' : '否'", "? 'Yes' : 'No'"],
      ["坐标系显示:", "Frame visibility:"],
      ["暂无坐标系", "No frames available"],
      ["? '显示' : '隐藏'", "? 'Visible' : 'Hidden'"],
      ["选择主文件", "Select primary file"],
      ["检测到多个 URDF 文件，请选择要使用的主文件：", "Multiple URDF files were detected. Choose the primary file to use:"],
      ["检测到多个 URDF 文件，请选择要Use的主文件：", "Multiple URDF files were detected. Choose the primary file to use:"],
      ["添加图片图层", "Add Image Layer"],
      ["AddImages图层", "Add Image Layer"],
      ["话题名称:", "Topic Name:"],
      ["话题Name:", "Topic Name:"],
      ["消息类型:", "Message Type:"],
      ["消息Type:", "Message Type:"],
      ["name: `图片 ${Object.keys(layerConfigs).filter(k => layerConfigs[k]?.id === 'image').length + 1}`", "name: `Image ${Object.keys(layerConfigs).filter(k => layerConfigs[k]?.id === 'image').length + 1}`"],
      ["name: `Images ${Object.keys(layerConfigs).filter(k => layerConfigs[k]?.id === 'image').length + 1}`", "name: `Image ${Object.keys(layerConfigs).filter(k => layerConfigs[k]?.id === 'image').length + 1}`"],
      ["确定", "Confirm"],
      ["取消", "Cancel"],
      ["未知错误", "Unknown error"],
      ["<span>显示</span>", "<span>Visible</span>"],
    ],
  },
  {
    file: "components/MapEditor.tsx",
    replacements: [
      ["name: '栅格地图'", "name: 'Occupancy Grid'"],
      ["name: 'Topo地图'", "name: 'Topology Map'"],
      ["初始化失败，使用默认配置...", "Initialization failed. Falling back to default settings..."],
      ["已设置起始点，点击设置结束点", "Start point set. Click again to choose the end point."],
      ["已绘制直线", "Line drawn"],
      ["已创建路线: ", "Route created: "],
      ["路线已存在", "Route already exists"],
      ["已添加点位: ", "Point added: "],
      ["拓扑地图已保存并发布", "Topology map saved and published"],
      ["保存成功，但发布失败", "Saved successfully, but publishing failed"],
      ["栅格地图已发布到 /map/update", "Occupancy grid published to /map/update"],
      ["栅格地图发布失败", "Failed to publish occupancy grid"],
      ["重做", "Redo"],
      ["撤销", "Undo"],
      ["无法获取机器人位置，请检查TF连接", "Unable to get robot pose. Check the TF connection."],
      ["已添加机器人当前位置为导航点: ", "Added current robot pose as a nav point: "],
      ["请输入地图名称", "Enter a map name"],
      ["没有可导出的地图数据", "No map data available for export"],
      ["地图已导出为 ${exportMapName.trim()}.zip", "Map exported as ${exportMapName.trim()}.zip"],
      ["导出地图失败:", "Failed to export map:"],
      ["导出地图失败", "Failed to export map"],
      ["请选择zip格式的地图文件", "Choose a .zip map file"],
      ["栅格地图导入成功", "Occupancy grid imported successfully"],
      ["拓扑地图导入成功", "Topology map imported successfully"],
      ["zip文件中没有找到有效的地图数据", "No valid map data found in the ZIP archive"],
      ["导入地图失败:", "Failed to import map:"],
      ["导入地图失败: ", "Failed to import map: "],
      ["地图编辑", "Map Editor"],
      ["导入地图zip文件", "Import map ZIP"],
      ["📥 导入地图", "📥 Import Map"],
      ["导出地图为map.zip", "Export map as map.zip"],
      ["📦 导出地图", "📦 Export Map"],
      ["保存拓扑地图", "Save topology map"],
      ["💾 保存", "💾 Save"],
      ["移动工具", "Move tool"],
      ["🖱️ 移动", "🖱️ Move"],
      ["添加拓扑点位", "Add topology point"],
      ["➕ 添加点位", "➕ Add Point"],
      ["拓扑连线", "Create topology route"],
      ["🔗 拓扑路径", "🔗 Topology Route"],
      ["绘制障碍物", "Paint obstacles"],
      ["🖌️ 障碍物绘制", "🖌️ Paint Obstacles"],
      ["擦除障碍物", "Erase obstacles"],
      ["🧹 橡皮擦", "🧹 Eraser"],
      ["直线绘制", "Draw line"],
      ["📏 直线绘制", "📏 Draw Line"],
      ["画笔大小:", "Brush Size:"],
      ["将机器人当前位置添加为导航点位", "Add current robot pose as a navigation point"],
      ["🤖 添加机器人当前位置", "🤖 Add Current Robot Pose"],
      ["点位属性", "Point Properties"],
      ["名称:", "Name:"],
      ["将机器人当前位置填入坐标", "Fill with current robot pose"],
      ["🤖 填入机器人位置", "🤖 Use Robot Pose"],
      ["确定", "Confirm"],
      ["取消", "Cancel"],
      ["已删除点位: ", "Point deleted: "],
      ["删除点位", "Delete Point"],
      ["路线属性", "Route Properties"],
      ["起点:", "Start:"],
      ["终点:", "End:"],
      ["控制器:", "Controller:"],
      ["目标检查器:", "Goal Checker:"],
      ["速度限制:", "Speed Limit:"],
      ["已删除路线: ", "Route deleted: "],
      ["删除路线", "Delete Route"],
      ["导出地图", "Export Map"],
      ["地图名称:", "Map Name:"],
      ["地图Name:", "Map Name:"],
      ["例如: map", "e.g. map"],
      ["鼠标:", "Cursor:"],
      ["机器人:", "Robot:"],
      ["导出", "Export"],
      ["未知错误", "Unknown error"],
    ],
  },
  {
    file: "components/layers/RobotLayer.tsx",
    replacements: [
      ["以下包未在配置中找到: ", "Packages missing from configuration: "],
      ["以下文件未找到: ", "Files not found: "],
      ["包 \"${packageName}\" 未在 URDF 配置中找到", "Package \"${packageName}\" is not present in the URDF configuration"],
      ["无法在已上传的文件中找到匹配的资源", "Could not find a matching uploaded asset"],
      ["URDF 配置中未找到任何包引用，无法加载模型", "No package references were found in the URDF configuration. Cannot load model."],
    ],
  },
];

for (const update of updates) {
  const filePath = path.join(vendorSrcRoot, update.file);
  let content = fs.readFileSync(filePath, "utf8");
  for (const [from, to] of update.replacements) {
    content = content.split(from).join(to);
  }
  fs.writeFileSync(filePath, content, "utf8");
}

console.log("Applied English replacements to vendored ros_web_gui_app sources.");
